### ISSUE TITLE
Behavior according to global brackets.json preferences file

### ISSUE THREAD

**Issue by glepretre** [MiguelCastillo/Brackets-wsSanitizer#10]
Hi,

I'm currently trying your extension and have a question about the preferences.

I understand I can define a project specific `.brackets.json` file at the project directory root, but can I use a global `path` rule in the classic `brackets.json` preferences file?

My use case is about Makefile(s): since it only support tabs as indent, I would like to turn off the sanitizer and use tabs for these files only.

Here's what I've tried in my `brackets.json`:

```
{
    "brackets-wsSanitizer.enabled": true,
    "path": {
        "Makefile": {
            "brackets-wsSanitizer.enabled": false,
            "useTabChar": true
        }
    }
}
```

**Comment by MiguelCastillo** [comment]
Yup, it should work with global preferences as well.  If you encounter issues, please let me know.

**Comment by glepretre** [comment]
Yes, I can confirm that with only your extension + [brackets-show-whitespace](https://github.com/DennisKehrig/brackets-show-whitespace), with the config given above, it does not work for me. No errors in DevTools. :smirk: 

Do you think it could be because the path `"Makefile"` has no extension? I have also tried `"**/*/Makefile"`.

**Comment by MiguelCastillo** [comment]
Hey thanks for reporting back :)  i will take a look in a moment to see how we can get this to work

**Comment by MiguelCastillo** [comment]
@glepretre I just tried your use case and you are correct.  the preference are not taking effect coming from the global `brackets.json`.  The reason is that `PathLayer` only applies to project settings. https://github.com/adobe/brackets/wiki/Preferences-System#preferences-system-basics

Let me take a closer at how we can get this to work.

**Comment by glepretre** [comment]
@MiguelCastillo Does that mean I am using the preferences system in a wrong way? I'm not sure to understand fully :smile:

**Comment by MiguelCastillo** [comment]
@glepretre Sorry I completely forgot about this issue.  So, unfortunately brackets preferences system does not allow configuring preferences for particular files in the global preferences file (user preferences).   At the current time, I don't think I can add this feature... But I am happy to take a PR to add more functionality for this though :)

**Comment by glepretre** [comment]
Ok, thanks for having taken the time to investigate this. :wink: So the solution is to overload the global preferences with a local `brackets.json` in each directory needing it?

**Comment by MiguelCastillo** [comment]
So I ended up adding support for the language layer so that you can specify whether or not a document should be sanitized on the file type.  But this only gets so far because `Makefile`s are not really a document type in Brackets.  I would like to create a small extension to allow defining languages via configuration...  You can take a look [here](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language).

So my suggestion for your particular problem is to map `Makefile` as a supported type.  Say, `bash`...  Then specify a `language` rule for `bash` to configure your `Makefile`s.  E.g.

```
{
    "language": {
        "basg": {
            "useTabChar": false,
            "tabSize": 4,
            "spaceUnits": 4,
            "brackets-wsSanitizer.enabled": false,
            "brackets-wsSanitizer.onopen": true
        }
    }
}
```

The reason to map `Makefile`s as `bash` is so that you can specify sanitizer settings for `bash` which will then apply to `Makefile`s.  Otherwise you will need to define a language via code as explained [here](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language).

I hope this helps! :)
