### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Equinox** [MiguelCastillo/Brackets-wsSanitizer#12]
Just wondering, there was [an extension](https://github.com/brad-jones/whitespace) that was basically a fork of this which sanitized the documents on load, as well as save. Any chance that'll be added to this extension? The [other extension is now abandoned and for me has stopped working.](https://github.com/brad-jones/whitespace/issues/1)

**Comment by MiguelCastillo** [comment]
@Equinox actually, I would like to add a message that tells the user if there is a mix of white spaces and tabs upon document load, and provide a way to sanitize if the user choses to.  Your request is definitely addressed then.  I am not too sure about letting sanitizer blindly fix up those files without letting the user know.

**Comment by Equinox** [comment]
What about a preference setting that enables that notification (on by default, of course)? I'd be more than happy with that. ;)

**Comment by MiguelCastillo** [comment]
yeah that's a great idea! :)

**Comment by Equinox** [comment]
I would love to help in anyway possible, although I don't think coding would be my strong suit (I'm not up to speed with Brackets' code), I am more than happy to vigorously test, whenever you've got something to test!

**Comment by MiguelCastillo** [comment]
Fixed with https://github.com/MiguelCastillo/Brackets-wsSanitizer/pull/13.

I ended up just leaving as a preference setting.  No UI at this point.  So you can configure an 'onopen' preference setting to enable the behavior.  Check  out the [docs](https://github.com/MiguelCastillo/Brackets-wsSanitizer#options) for an example.

I will be publishing this in soon, but in the meantime you can install the extension from Git to get this feature.  Let me know if you run into issues :)

**Comment by Equinox** [comment]
Damn, I just saw the notification, you're a machine! ;)

**Comment by MiguelCastillo** [comment]
hahaha - i have been meaning to add this... so you literally kicked me out of my couch to get this done :)  Thank you!

**Comment by Equinox** [comment]
Sadly, same as the other extension it doesn't work for me on document load. :(

**Comment by MiguelCastillo** [comment]
@Equinox so you installed the extension from git and it does not work?  Where do you put your `.brackets.json` file?  Do you mind sharing a screenshot that show where your `.brackets.json` is located?

Also, is the file you are expecting to be sanitized in your project?

**Comment by Equinox** [comment]
I git cloned the repo to an empty file in the extensions folder. 
[This](http://i.imgur.com/QgQO6Ny.png) is where my brackets.json file is.
[This](http://i.imgur.com/jUtIrxG.png) basically shows what I'm dealing with.

**Comment by MiguelCastillo** [comment]
Do you think you can share your gulpfile with me?  You can email it to me if you prefer... manchagnu@gmail.com.

**Comment by Equinox** [comment]
I removed all extensions again but this one, when the preference is space: 4, and there's a file (any file) that has some tag with only 2 indentation it never changes. File save and load does not change it at all. 

In other words, all files are giving me this same error. No specific file type or content (besides 2 spaced ones).

**Comment by MiguelCastillo** [comment]
@Equinox if you open the main file for your installed sanitizer, do you see this https://github.com/MiguelCastillo/Brackets-wsSanitizer/blob/master/main.js#L36?

**Comment by Equinox** [comment]
Assuming I'm not missing some special way to look at it, yeah.

**Comment by MiguelCastillo** [comment]
If you have two spaces in your file, and brackets is configured to insert 4 spaces, sanitizer shouldn't do anything with the file.

When you open the file that does not get sanitized, are you opening it by navigating the file tree in brackets in your current project or do you go to the brackets file menu and choose some random file?

* The use case I have targeted is that files should be opened from the file tree.

Also, to good way to test this feature is to take a file that has tabs, Brackets is set to spaces, and you open the file from the file tree...  I am not exactly how this would not work :-/

**Comment by Equinox** [comment]
I'm opening it by using the file tree.

Two things: 
From your first point in your last comment, are you saying this isn't supposed to get sanitized? ![](http://i.imgur.com/aZ4TjaN.png)

And, do you have a sample file/something that I can try to test? If it works for you it'd be easier to see if it's only me it doesn't work for. 

BTW, thanks for your time!

**Comment by Equinox** [comment]
Regarding that first point, I had a file with just this:

<pre>{
  "directory": "bower_components"
}</pre>

And still, even with the space setting set to 4, it never changed from 2 (unless I'm misunderstanding and it is not supposed to?).

**Comment by MiguelCastillo** [comment]
Yeah, sanitizer is not designed to do that.  The logic is based is based on replacing tabs with spaces, and spaces with tabs...  Only replacing multiple amounts.  For example, if you have a file that has spaces, and Brackets is configured to use tabs, I will take the number of spaces in a tab configured in brackets and convert as many spaces to tabs.  Any overflow will be left as spaces.  That is to say that I you have a file with 6 white spaces leading spaces, and Brackets is configured to tabs of 4 spaces, then sanitizer will convert those 6 spaces to 1 tab plus 2 spaces...

I havent put much thought into converting from 4 spaces down to 2, for example...  That seems like it will lead to code formatting issues.  Let me think about that issue, but that's not really related to sanitizing a file upon opening.

All my files convert correctly from spaces to tabs, and vice versa.  So, do this.  Enable `onopen`, set Brackets to tabs, and open any file that has all white spaces.  You may want to install https://github.com/DennisKehrig/brackets-show-whitespace to see the change...  You can try that on this project https://github.com/MiguelCastillo/Brackets-Harmony

**Comment by Equinox** [comment]
So, just to lastly confirm, this is not supposed to change files that have say 2 spaces  for indentation throughout the file, to whatever you've currently got it set to (ie 4 spaces)?

**Comment by Equinox** [comment]
Just to add to that, if it is wrong, any plans to possibly make it either an option of this extension or another? It's somewhat on the scope of whitespace sanitization.

**Comment by MiguelCastillo** [comment]
@Equinox correct, this extension does not change the number of spaces per line if the file is already spaces.  At least not directly.  How I have handled that problem before is via sequence of steps.  The steps below change the document from 2 spaces to 4 spaces.

1. Configure brackets to use tabs.
2. Set the number of spaces per tab that match the current document. (2 spaces).
3. Sanitize the document to change from spaces to tabs.
4. Now adjust the number of spaces per tabs to the new number of spaces you want. (4 spaces).
5. Sanitize document to change the number of spaces in a tab to 4.
6. Change brackets settings back to spaces.
7. The whole document should be based on 4 spaces.

I know it's a ridiculous list of steps.  It's not as bad when you actually do it.  But the reason why this isn't automated is because of step number 2.  Which involves knowing the initial number of spaces in the document.  The whole thing is based on knowing a seed number...  The number brackets was configured with when the document was created. 2 spaces, 4 spaces...

The somewhat difficult problem is that I will need to analyze the document to infer that initial number of spaces.  Once I know that initial value, the rest is easy.  That number is important so that I know if a line that has 8 spaces means that the document use 2 spaces and there are 4 indentations, or uses 4 spaces and there are 2 indentations.

This is why I have left this particular problem to tools like beautify.  They do a more complete lexical analysis on the file.

BUT, I am always happy to accept PRs if you want to give it try.  I can help you along the way.  :)

**Comment by Equinox** [comment]
That makes sense, thanks for explaining! I'll give making it a go. 

I'll close this as it was my misunderstanding, not a bug. :)

**Comment by MiguelCastillo** [comment]
@Equinox I added a small UI to notify the user when they open a document and there is a mixture of tabs and spaces... :)

**Comment by Equinox** [comment]
Just got the notification in my brackets.json file, looking good!
